PROYECTO_EMPLEADOS/empleado/departamento/urls.py
from django.urls import path
from departamento.views import newDepaView, DepartamentoListView

urlpatterns = [
    path('lista/', DepartamentoListView.as_view(), name='listaDepa'),
    path('new/',newDepaView.as_view(),name='new_department'),
]

PROYECTO_EMPLEADOS/empleado/empleado/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from persona.views import home

urlpatterns = [
    path('admin/', admin.site.urls),
    #Home
    path('',home,name="index"),
    path('departamento/', include('departamento.urls')),
    path('empleado/', include('persona.urls')),
] + static(settings.MEDIA_URL,document_root = settings.MEDIA_ROOT)

PROYECTO_EMPLEADOS/empleado/persona/urls.py
from django.urls import path
from persona.views import ListaEmpleadosByArea, listaEmpleadosAdmin, EmpleadoUpdateView,EmpleadoDeleteView,EmpleadoCreateView
from persona.views import listaEmpleados
from persona.views import verEmpleado

urlpatterns = [
    path('lista/', listaEmpleados.as_view(), name='lista_empleados'),
    path('empleado/<int:id>',verEmpleado, name = 'empleado'),
    path('lista/area/<shorname>', ListaEmpleadosByArea.as_view(), name='empleados_area'),
    path('lista/empleados/admin', listaEmpleadosAdmin.as_view(), name='empleados_admin'),

    #CRUD
    path('add/', EmpleadoCreateView.as_view(), name='empleado_add'),
    path('update/empleado/<pk>',EmpleadoUpdateView.as_view(),name="update_empleado"),
    path('delete/empleado/<pk>/', EmpleadoDeleteView, name='delete_empleado'),
]

PROYECTO_EMPLEADOS/empleado/departamento/models.py
from tabnanny import verbose
from django.db import models

# Create your models here.
class Departamento(models.Model):
    #Atributes
    name = models.CharField('Name',max_length=50)
    short_name = models.CharField('Short name', max_length=20)

    #The class meta you can get better presentation of your data in the admin section
    class Meta:
        #Modifie the title
        verbose_name = 'Department'
        #Ordering 
        ordering = ['-name']
        #prevents register the same register two times
        unique_together = ('name','short_name')
    def __str__(self):
        return self.name + "-" + self.short_name

PROYECTO_EMPLEADOS/empleado/persona/models.py
from tabnanny import verbose
from django.db import models
from departamento.models import Departamento
# Create your models here.
    #habilities
class Habilidades(models.Model):
    habilidad = models.CharField('Habilidad',max_length=50)
    class meta:
        verbose_name = 'Hability'
    def __str__(self) -> str:
        return str(self.id) +'-'+ self.habilidad

class Empleado(models.Model):        
    #types
    JOB_CHOICES = (
        ('0','Contador'),
        ('1','Administrador'),
        ('2','Economista'),
        ('3','Otro'),
    )
    #Att
    first_name = models.CharField('Name' , max_length=60)
    last_name = models.CharField('Last name' , max_length=60)
    job = models.CharField('Job',max_length= 1,choices=JOB_CHOICES)
    #The foreing key
    departamento = models.ForeignKey(Departamento, on_delete=models.CASCADE)
    image = models.ImageField(upload_to='empleado', blank = True, null=True)
    #A relations many to many
    habilidades = models.ManyToManyField(Habilidades)
    def __str__(self) -> str:
        return str(self.id) +'-'+self.first_name +'-'+ self.last_name

PROYECTO_EMPLEADOS/empleado/departamento/forms.py
from django import forms

#Import models
class newDepartamentoForm(forms.Form):
    nombre = forms.CharField(max_length=50)
    apellido = forms.CharField(max_length=50)
    departamento = forms.CharField(max_length=50)
    short_name = forms.CharField(max_length=20)
    

PROYECTO_EMPLEADOS/empleado/persona/forms.py
from django import forms
from persona.models import Empleado
#Create a form
class EmpleadoForm(forms.ModelForm):
    
    class Meta:
        model = Empleado
        fields = '__all__'
        #Widgets---
        widgest = {
            'first_name': forms.TextInput( 
                attrs={
                    'placeholder':'Ingrese su nombre'
                }
            )
        }

PROYECTO_EMPLEADOS/empleado/departamento/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic.edit import FormView
from django.views.generic import ListView
from departamento.forms import newDepartamentoForm

from persona.models import Empleado
from departamento.models import Departamento
# Create your views here.

class DepartamentoListView(ListView):
    model = Departamento
    template_name = "departamento/lista.html"
    context_object_name = "departamentos"


class newDepaView(FormView):
    template_name = 'departamento/new_depa.html'
    form_class = newDepartamentoForm
    success_url = reverse_lazy('listaDepa')

    def form_valid(self, form):

        depa = Departamento(
            name=form.cleaned_data['departamento'],
            short_name=form.cleaned_data['short_name']
        )
        depa.save()
        nombre = form.cleaned_data['nombre']
        apellido = form.cleaned_data['apellido']
        Empleado.objects.create(
            first_name = nombre,
            last_name = apellido,
            job = '1',
            departamento=depa,
        )
        return super(newDepartamentoForm,self).form_valid(form)

PROYECTO_EMPLEADOS/empleado/persona/views.py
from django.urls import reverse_lazy
from django.views.generic import ListView, UpdateView, CreateView
from django.shortcuts import get_object_or_404, redirect, render

#Import models
from persona.models import Empleado
#Import forms
from persona.forms import EmpleadoForm

# Create your views here.
##THE HOME PAGE
def home(request):
    #Take all 
    return render(request,'inicio.html')

#EMPLEADO
#Vista basada en clases
class listaEmpleados(ListView):
    template_name = 'lista_empleados.html'
    paginate_by = 4
    ordering = 'first_name'
    context_object_name = 'empleados'

    def get_queryset(self):
        key_word = self.request.GET.get('kword','')
        lista = Empleado.objects.filter(
            first_name__icontains = key_word
        )
        return lista

#Lista empleados by area
class ListaEmpleadosByArea(ListView):
    template_name = 'personas/lista_area.html'
    context_object_name = 'empleados'
    def get_queryset(self):
        area = self.kwargs['shorname']
        lista = Empleado.objects.filter(
            departamento__short_name = area
        )
        return lista
#Lista empleados admin
class listaEmpleadosAdmin(ListView):
    model = Empleado
    template_name = 'lista_empleados_admin.html'
    paginate_by = 10
    ordering = 'first_name'
    context_object_name = 'empleados'

##CRUD
#Crear

class EmpleadoCreateView(CreateView):
    model = Empleado
    template_name = "personas/empleado_add.html"
    fields = '__all__'
    success_url = reverse_lazy('lista_empleados')

#Actualizar
class EmpleadoUpdateView(UpdateView):
    model = Empleado
    template_name = "personas/update.html"
    fields = [
        'first_name',
        'last_name',
        'job',
        'departamento',
        'habilidades'
    ]
    success_url = reverse_lazy('empleados_admin')

##funciones
#Eliminar
def EmpleadoDeleteView(request,pk):
    empleado = get_object_or_404(Empleado,pk=pk)
    if empleado:
        empleado.delete()
    return redirect('empleados_admin')


#Ver empleado
def verEmpleado(request, id):
    #Traemos al empleado
    empleado = get_object_or_404(Empleado,pk=id)
    return render(request,'detail_empleado.html',{'empleado':empleado})

PROYECTO_EMPLEADOS/empleado/templates/departamento/lista.html
{% extends 'index.html' %}
{% load static %}


{% block title %}Lista departamentos{% endblock %}

{% block content %}
    {% include "includes/header.html" %}
    <div class="grid-container">
        <div class="grid-x">
            <h1 class="cell">Lista departamento</h1>
            <div class="cell">
                <table>
                    <tbody>
                        {% for depas in departamentos  %}
                        <tr>
                            <td>{{depas.name}}</td>
                            <td>{{depas.short_name}}</td>
                            <td><a class="button success" href="{% url 'empleados_area' depas.short_name %}">Ver departamento</a></td>  
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
{% endblock  %}

PROYECTO_EMPLEADOS/empleado/templates/departamento/new_depa.html
{% extends 'index.html' %}
{% load static %}


{% block title %}Añadir Departamento{% endblock %}

{% block content %}
    {% include "includes/header.html" %}
    <div class="grid-container">
        <div class="grid-x">
            <h1 class="cell">Registrar departamento</h1>
        </div>
        <div class="cell">
            <form action="" method="POST" class="cell callout grid-x grid-margin-x"> {% csrf_token %}
                <div class="large-6 cell">
                    <label>Nombre:
                        {{form.nombre}}
                    </label>
                </div>
                <div class="large-6 cell">
                    <label>Apellido:
                        {{form.apellido}}
                    </label>
                </div>
                <div class="large-6 cell">
                    <label>departamento:
                        {{form.departamento}}
                    </label>
                </div>
                <div class="large-6 cell">
                    <label>Nombre corto:
                        {{form.short_name}}
                    </label>
                </div>
                <div class="large-6 cell">
                    <button type="submit" class="button success">Registrar</button>
                </div>
            </form>
        </div>
    </div>
{% endblock  %}

PROYECTO_EMPLEADOS/empleado/templates/detail_empleado.html
{% extends 'index.html' %}
{% load static %}


{% block title %}Empleado No. {{empleado.id}}{% endblock %}

{% block content %}
    {% include "includes/header.html" %}
    <div class="grid-container">
        <div class="grid-x grid-margin-x align-center">
            <div class="card cell large" style="width: 300px;">
                <div class="card-divider">
                  {{empleado.get_job_display}}
                </div>
                {% if empleado.image %}
                    <img src="{{empleado.image.url}}">
                {% endif %}
                    <img src="{% static 'img/foto1.jpg' %}">
                <div class="card-section align-center">
                  <h4>{{empleado.first_name}} {{empleado.last_name}}</h4>
                  <p>{{empleado.departamento.name}}</p>
                  <p><span class="label">Habilidades:
                    <ul class="vertical menu">
                        {% for h in empleado.habilidades.all %}
                        <li>{{h.habilidad}}</li>
                        {% endfor %}     
                    </ul>
                  </span>
                  </p>
                </div>
              </div>
        </div>
    </div>
{% endblock  %}

PROYECTO_EMPLEADOS/empleado/templates/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/foundation.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/app.css' %}">
    <title>{% block title %} {% endblock %}</title>
</head>
<body>
    <header>
    </header>
    {% block content %}
    {% endblock %}
    <script src="{% static 'js/vendor/jquery.js' %}"></script>
    <script src="{% static 'js/vendor/what-input.js' %}"></script>
    <script src="{% static 'js/vendor/foundation.min.js' %}"></script>
    <script>
      $(document).foundation();
    </script>
</body>
</html>

PROYECTO_EMPLEADOS/empleado/templates/inicio.html
{% extends 'index.html' %}
{% load static %}


{% block title %}Pagina de inicio de empleados {% endblock %}

{% block content %}
    {% include "includes/header.html" %}
    <h1>Pagina de inicio</h1>
    <!--Inicio de imagen-->
    <div class="orbit" role="region" aria-label="Favorite Space Pictures" data-orbit>
        <div class="orbit-wrapper">
          <div class="orbit-controls">
            <button class="orbit-previous"><span class="show-for-sr">Previous Slide</span>&#9664;&#xFE0E;</button>
            <button class="orbit-next"><span class="show-for-sr">Next Slide</span>&#9654;&#xFE0E;</button>
          </div>
          <ul class="orbit-container">
            <li class="is-active orbit-slide">
              <figure class="orbit-figure">
                <img class="orbit-image" src="{% static 'img/foto1.jpg' %}" alt="Space">
                <figcaption class="orbit-caption">Space, the final frontier.</figcaption>
              </figure>
            </li>
            <li class="orbit-slide">
              <figure class="orbit-figure">
                <img class="orbit-image" src="{% static 'img/foto1.jpg' %}" alt="Space">
                <figcaption class="orbit-caption">Lets Rocket!</figcaption>
              </figure>
            </li>
          </ul>
        </div>
      </div>
    <!--Inicio de imagen-->
<!--Bienvenida-->  
      <div class="grid-x align-center">
        <h1 class="cell large-12 align-center" style="text-align:center;">Bienvenido al sistema de registro de empleados</h1>
        <div class="cell large-12 align-center">
            <div class="callout success" style="text-align:center;">
                <h5>Este web esta hecha con django y css fundation</h5>
                <a href="#">Ver empleados</a>
            </div>
        </div>
      </div>
<!--Fin-->  
{% endblock  %}

PROYECTO_EMPLEADOS/empleado/templates/lista_empleados.html
{% extends 'index.html' %}
{% load static %}


{% block title %}Lista{% endblock %}

{% block content %}
    {% include "includes/header.html" %}
    <div class="grid-container">
        <div class="grid-x">
            <h1 class="cell">Lista empleados</h1>
            <form method="GET" class="cell grid-x grid-margin-x"> {% csrf_token %}
                <div class="cell large-7">
                    <input type="text" name="kword" id="kword" placeholder="Buscar empleado">
                </div>
                <div class="cell large-2">
                    <button class="submit success button">Buscar</button>
                </div>
            </form>
            <div class="cell">
                <table>
                    <thead>
                      <tr>
                        <th width="200">ID</th>
                        <th>Nombres</th>
                        <th width="150">Apellidos</th>
                        <th width="150">Departamento</th>
                        <th width="150"></th>
                      </tr>
                    </thead>
                    <tbody> 
                      {% for e in empleados %}
                        <tr>
                            <td> {{e.id}} </td>
                            <td>{{e.first_name}}</td>
                            <td>{{e.last_name}}</td>
                            <td>{{e.departamento}}</td>
                            <td><a class="clear button warning" href="{% url 'empleado' e.id %}">Ver</a></td>
                        </tr>    
                      {% endfor %}
                  </table>
            </div>
            <div class="cell">
                {% if is_paginated %}
                <nav aria-label="Pagination">
                    <ul class="pagination">  
                      {% if page_obj.has_previous %}   
                      <li class="pagination-previous">
                          <a href="?page={{page_obj.previous_page_number}}" aria-label="Page 2">Atras</a>
                      </li>
                      {% endif %}
                      {% for pagina in paginator.page_range %}

                        {% if pagina == page_obj.number %} 
                        <li class="current"><span class="show-for-sr">You're on page</span>{{pagina}}</li>
                        {% else %}
                        <li><a href="?page={{pagina}}" aria-label="Page 2">{{pagina}}</a></li>      
                        {% endif %}

                      {% endfor %}

                      {% if page_obj.has_next %}  
                      <li class="pagination-next">
                        <a href="?page={{page_obj.next_page_number}}" aria-label="Page 2">Next</a>
                      </li>
                      {% endif %}
                    </ul>
                  </nav>                    
                {% endif %}
            </div>
        </div>
    </div>
{% endblock  %}

PROYECTO_EMPLEADOS/empleado/templates/lista_empleados_admin.html
{% extends 'index.html' %}
{% load static %}


{% block title %}Lista{% endblock %}

{% block content %}
    {% include "includes/header.html" %}
    <div class="grid-container">
        <div class="grid-x">
            <h1 class="cell">Lista empleados</h1>
            <div class="cell">
                <table>
                    <thead>
                      <tr>
                        <th width="200">ID</th>
                        <th>Nombres</th>
                        <th width="150">Apellidos</th>
                        <th width="150">Departamento</th>
                        <th width="150"></th>
                      </tr>
                    </thead>
                    <tbody> 
                      {% for e in empleados %}
                        <tr>
                            <td> {{e.id}} </td>
                            <td>{{e.first_name}}</td>
                            <td>{{e.last_name}}</td>
                            <td>{{e.departamento}}</td>
                            <td>
                                <a class="button button success" href="{% url 'update_empleado' e.id %}">Editar</a>
                            </td>
                            <td>
                                <a class="button button alert" href="{% url 'delete_empleado' e.id %}">Eliminar</a>
                            </td>
                        </tr>    
                      {% endfor %}
                  </table>
            </div>
            <div class="cell">
                {% if is_paginated %}
                <nav aria-label="Pagination">
                    <ul class="pagination">  
                      {% if page_obj.has_previous %}   
                      <li class="pagination-previous">
                          <a href="?page={{page_obj.previous_page_number}}" aria-label="Page 2">Atras</a>
                      </li>
                      {% endif %}
                      {% for pagina in paginator.page_range %}

                        {% if pagina == page_obj.number %} 
                        <li class="current"><span class="show-for-sr">You're on page</span>{{pagina}}</li>
                        {% else %}
                        <li><a href="?page={{pagina}}" aria-label="Page 2">{{pagina}}</a></li>      
                        {% endif %}

                      {% endfor %}

                      {% if page_obj.has_next %}  
                      <li class="pagination-next">
                        <a href="?page={{page_obj.next_page_number}}" aria-label="Page 2">Next</a>
                      </li>
                      {% endif %}
                    </ul>
                  </nav>                    
                {% endif %}
            </div>
        </div>
    </div>
{% endblock  %}

PROYECTO_EMPLEADOS/empleado/templates/personas/empleado_add.html
{% extends 'index.html' %}
{% load static %}


{% block title %}Añadir empleado{% endblock %}

{% block content %}
    {% include "includes/header.html" %}
    <div class="grid-container">
        <div class="grid-x">
            <h1 class="cell">Añadir empleado</h1>
        </div>
        <div class="cell">
            <form action="" method="POST" class="grid-x grid-margin-x" enctype="multipart/form-data"> {% csrf_token %}
                <div class="large-6 cell">
                    <label>Nombre:
                        {{form.first_name}}
                    </label>
                </div>
                <div class="large-6 cell">
                    <label>Apellido:
                        {{form.last_name}}
                    </label>
                </div>
                <div class="large-6 cell">
                    <label>Trabajo:
                        {{form.job}}
                    </label>
                </div>
                <div class="large-6 cell">
                    <label>Departamento:
                        {{form.departamento}}
                    </label>
                </div>
                <div class="large-6 cell">
                    <label>habilidades:
                        {{form.habilidades}}
                    </label>
                </div>
                <div class="large-6 cell">
                    <label>Avatar:
                        {{form.image}}
                    </label>
                </div>
                <div class="large-6 cell">
                    <button type="submit" class="button success">Agregar</button>
                </div>
            </form>
        </div>
    </div>
{% endblock  %}

PROYECTO_EMPLEADOS/empleado/templates/personas/lista_area.html
{% extends 'index.html' %}
{% load static %}


{% block title %}Lista empleados por departamento{% endblock %}

{% block content %}
    {% include "includes/header.html" %}
    <div class="grid-container">
        <div class="grid-x">
            <h1 class="cell">Lista empleados</h1>
            <div class="cell">
                <table>
                    <thead>
                      <tr>
                        <th width="200">ID</th>
                        <th>Nombres</th>
                        <th width="150">Apellidos</th>
                        <th width="150">Departamento</th>
                        <th width="150"></th>
                      </tr>
                    </thead>
                    <tbody> 
                      {% for e in empleados %}
                        <tr>
                            <td> {{e.id}} </td>
                            <td>{{e.first_name}}</td>
                            <td>{{e.last_name}}</td>
                            <td>{{e.departamento}}</td>
                            <td><a class="clear button warning" href="{% url 'empleado' e.id %}">Ver</a></td>
                        </tr>    
                      {% endfor %}
                  </table>
            </div>
            <div class="cell">
                {% if is_paginated %}
                <nav aria-label="Pagination">
                    <ul class="pagination">  
                      {% if page_obj.has_previous %}   
                      <li class="pagination-previous">
                          <a href="?page={{page_obj.previous_page_number}}" aria-label="Page 2">Atras</a>
                      </li>
                      {% endif %}
                      {% for pagina in paginator.page_range %}

                        {% if pagina == page_obj.number %} 
                        <li class="current"><span class="show-for-sr">You're on page</span>{{pagina}}</li>
                        {% else %}
                        <li><a href="?page={{pagina}}" aria-label="Page 2">{{pagina}}</a></li>      
                        {% endif %}

                      {% endfor %}

                      {% if page_obj.has_next %}  
                      <li class="pagination-next">
                        <a href="?page={{page_obj.next_page_number}}" aria-label="Page 2">Next</a>
                      </li>
                      {% endif %}
                    </ul>
                  </nav>                    
                {% endif %}
            </div>
        </div>
    </div>
{% endblock  %}

PROYECTO_EMPLEADOS/empleado/templates/personas/update.html
{% extends 'index.html' %}
{% load static %}


{% block title %}Editar Empleado No. {{empleado.id}}{% endblock %}

{% block content %}
    {% include "includes/header.html" %}
    <div class="grid-container">
        <div class="grid-x">
            <h1 class="cell">Modificar Empleado</h1>
        </div>
        <div class="cell">
            <form action="" method="POST" class="grid-x grid-margin-x" enctype="multipart/form-data"> {% csrf_token %}
                <div class="large-6 cell">
                    <label>Nombre:
                        {{form.first_name}}
                    </label>
                </div>
                <div class="large-6 cell">
                    <label>Apellido:
                        {{form.last_name}}
                    </label>
                </div>
                <div class="large-6 cell">
                    <label>Trabajo:
                        {{form.job}}
                    </label>
                </div>
                <div class="large-6 cell">
                    <label>Departamento:
                        {{form.departamento}}
                    </label>
                </div>
                <div class="large-6 cell">
                    <label>habilidades:
                        {{form.habilidades}}
                    </label>
                </div>
                <div class="large-6 cell">
                    <label>Avatar:
                        {{form.image}}
                    </label>
                </div>
                <div class="large-6 cell">
                    <button type="submit" class="button success">Actualizar</button>
                </div>
                
            </form>
        </div>
    </div>
{% endblock  %}